[phases.setup]
nixPkgs = ["nodejs", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
  "chmod +x node_modules/.bin/*",
  "pnpm run build"
]

[start]
cmd = "npx serve dist -s -p 3000"
