[phases.setup]
nixPkgs = ["nodejs", "pnpm"]

[phases.install]
cmds = [
  "pnpm install --frozen-lockfile",
  "pnpm install picomatch@4.0.2"
]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "npx serve dist -s -p 3000"
